Djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miniapp.urls',)),
    path('', include('userauth.urls',)),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

miniapp/urls.py
from django.urls import path

from . import views

app_name = 'miniapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.appview, name="dashboard"),
    path('booking', views.booking, name='booking'),
    path('user-panel', views.userPanel, name='userPanel'),
    path('staff-panel', views.staffPanel, name='staffPanel'),
]

userauth/urls.py
from django.urls import path

from . import views

app_name = 'userauth'

urlpatterns = [
    path('login/', views.t_login, name='login'),
    path('signup/', views.t_sign_up, name='signup' ),
    path('logout/', views.logoutUSer,name='logout')
]

templates/booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>online Booking</title>
</head>
<body background="{%static 'img/image2.jpg' %}" style="background-size: cover; background-color: rgba(117, 63, 8, 0.5); background-blend-mode: multiply;">

    {% if user.is_authenticated %}
<h1 class="text-center  mt-3" style="font-size: 3.5rem;"><center><u>Online Booking</u>  </center></h1>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <form method="post" action="{% url 'miniapp:booking' %}" class="me-2 ms-2" required>
        {% csrf_token %}

        <div style="padding-top: 5px;"><center>

            <!--input service-->
        <div>
            <h3 class="" style="font-size: 2rem;">Select Service:</h3>
            <select class="form-select fs-3" name="service" style="width: 200px; margin-bottom:20px ;">
                <option value="Doctor care" style="font-size: 1rem;">Doctor care</option>
                <option value="Nursing care" style="font-size: 1rem;">Nursing care</option> 
            </select>
        </div>
            <!--input day-->
            <div class="mt-3">
                <h3 class="" style="font-size: 2rem;">Select Day:</h3>
                <select class="form-select fs-3" name="day" style="width: 200px; margin-bottom:20px;">
                    {% for validateWeekday in validateWeekdays %}
                    <option value="{{validateWeekday}}" style="font-size: 1rem;">{{validateWeekday}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mt-3">
                <h3 class="" style="font-size: 2rem;">Select Time:</h3>
                <select class="form-select fs-3" name="times" style="width: 200px; margin: bottom 20px;">
                    {% for times in times %}
                    <option value="{{times}}" style="font-size: 1rem;">{{times}}</option>
                    {% endfor %}
                </select>
            </div>


        </div></center>
            <br/><center>
            <button type="submit" class="btn btn-primary text-white" style="margin-top: 50px; color: black;">Continue</button></center>
        </div>
    </form>
</div>

{% else %}

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <h1 class="p-2  me-3">You Are Not Signed in!</h1>
    <a href="{% url 'miniapp:login' %}" class="btn btn-primary shadow text-center">Sign in</a>
</div>

{% endif %}
    
</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<head>
    <title>
        My Dashboard
    </title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   </body>
 </html>
    <style>
        section {
        padding: 50px 0px;
    }
    </style>
    
    </head>


    <body>

        <nav class="navbar navbar-expand-lg fixed-top navbarScroll" style="background: transparent;">
            <div class="container" style="margin-left: auto;">
                <a class="navbar-brand" href="#"> <h3 style= "font-size:40px "><img src="{% static 'img/App_Logo-removebg-preview.png' %}"></h3></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#home"><h3 style="font-size :25px; font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">Home</h3></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#about"><h3 style="font-size :25px; font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">About Doctor</h3></a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="#contact"><h3 style="font-size :25px; font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">Contact</h3></a>
                        </li>

                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'miniapp:staffPanel' %}"><h3 style="font-size :25px; font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">Staff Panel</h3></a>                     
                        </li>

                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'miniapp:userPanel' %}"><h3 style="font-size :25px; font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">User Panel</h3></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'userauth:logout' %}"><h3 style="font-size :25px; font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">Logout</h3></a>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>


        <!-- main banner -->
    <section class="bgimage2" id="home">
        <div class="container-fluid">
            <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 hero-text">
                
                <br><br>
                <h2 style="font-family:Georgia, 'Times New Roman', Times, serif;" class="hero_title" >Welcome ....</h2>
                <p class="hero_desc" style="font-family:Georgia, 'Times New Roman', Times, serif;">Book your appointment and get consulted from our campus doctor</p>
                <center>
                <!-- <button onclick="myFunction()" id="book" style="background-color: black;border-color: black;" type="button" class="btn btn-success mt-3 text-center">Book Now</button>  
                <br></br>
                <input type="date" id="myDate" value="2021-02-09">
                <br>
                
                <p id="demo"></p>
                <script>
                    function myFunction() {
                      var x = document.getElementById("myDate").value;
                      document.getElementById("demo").innerHTML = x;
                    }
                    </script> -->

                <a type="button" class="btn btn-primary shadow mt-5" href="{% url 'miniapp:booking' %}" style="background-color: black; color: whitesmoke; border: black;">Book now!</a>
             </center>
            </div>
            </div>

            
                
            
            
          
          

        </div>
    </section>
    

    <section id="about" style="background-color: #95cad4;" >
        <div class="container-fluid" >
            <div class="container">
                <div class="row">
        
                <div class="col-lg-12 text-center" style="padding-bottom: 3%">
                    <p style="display:inline; font-size: 35px">About the Doctor</p>
                    <center>
                    <hr style="width: 200px; height: 1px; border:none;color:#333;background-color:#333;">
                    
                      <p style="max-width: 500px; line-height: 27px; color: black; " class="text-muted"><i> A small brief about the doctor </i>
                      </p>
                    </center>
                    <div class="row">
                        <div class="col-md-1">
                            <img src="https://img.freepik.com/free-vector/hand-drawn-cartoon-doctor-woman-presenting-vaccine-syringe_40876-3160.jpg?w=2000" alt="" style="margin-left: 45px; height: 350px; width: 400px;" >
                        </div>
                        <div class="col-md-11">
                    <h4 style=" margin-left:10px; color:rgb(36, 49, 37); font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">
                       
                        <ul class="ul1">
                            <li>Name: Dr. Dorothi Fernandes </li><br>
                        <li>Gender: Female </li><br>
                        <li>Education: MBBS, MD, FRCS</li><br>
                        <li>Available days: Mon - Fri</li><br>
                        <li>Available time: 3pm - 7pm</li><br>
                        <li>Location: Central Campus (2nd Floor)</li>
                    </ul>
                    </h4>
                </div>
                
                </div>
                  </div>
                </div>
                
            </div>
       </section>

<section id="contact" class="bgimage">
<!-- FOOTER -->
<!-- Footer -->
<footer class="text-center text-white">
    <!-- Grid container -->
    <div class="container">
      <!-- Section: Social media -->
      <h3>Contact</h3>
      
        <!-- Facebook -->
        <a class="btn btn-outline-light  mt=0" href="https://www.facebook.com/lavasa.christuniversity" role="button"
          ><i class="fa fa-facebook-square"></i
        ></a>
  
        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating mt=0" href="https://www.linkedin.com/in/christlavasa/" role="button"
          ><i class="fa fa-linkedin-square"></i
        ></a>
  
        <!-- Google -->
        <a class="btn btn-outline-light btn-floating mt=0" href="https://lavasa.christuniversity.in/" role="button"
          ><i class="fa fa-google-plus-square"></i
        ></a>
  
      
  </div>

      <!-- Section: Links -->
    <section class="bgimage1 container mt-3">
        
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-md-3 ">
            <h5 class="text-uppercase">Email</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">doctor@gmail.com</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-md-3">
            <h5 class="text-uppercase">Website</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="https://lavasa.christuniversity.in/" class="text-white">lavasa.christuniversity.in</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-md-3">
            <h5 class="text-uppercase">Phone</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">1800-123-2009</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-md-3 ">
            <h5 class="text-uppercase">University Email</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="mail.lavasa@christuniversity.in" class="text-white">mail.lavasa@christuniversity.in</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
        </div>
    
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->
</footer>
</section>
  
  <!-- Footer -->

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  <title>UniDoc</title>
</head>
<body background="{%static 'img/bg12.jpg' %}" style="background-size: cover; background-color: rgba(138, 156, 177, 0.5); background-blend-mode: multiply;">

  <div class="container">
    <div class="row">
      <img src="{% static 'img/App_Logo-removebg-preview.png' %}" alt="" class="img-fluid mx-auto d-block float-center r-50" style="width: 400px; height:225px; padding-top: 20px; padding-left: 2px; padding-top: 75px;">
    </div>
    <div class="card text-center" style="margin-top: 150px; background-color: transparent;">
        <div class="card-body">
          <h4 class="card-title" style="color: black;">Welcome to the doctors Appointment App</h4>
          <a href="{% url 'miniapp:dashboard' %}" class="btn btn-primary" style="background-color: black; color: whitesmoke;">Login</a>
        </div>
      </div>
</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <title>Login Page</title>
</head>
<body>

    <section class="vh-100 bg-image"
    style="background-image: url('https://wallpaperaccess.com/full/958470.jpg');">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Login</p>
      
                      <form class="mx-1 mx-md-4" method="post">
                        {% csrf_token %}
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="email_address">Your Email</label>
                            <input type="email" name="email_address" id="email_address" class="form-control" />
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="password">Password</label>
                            <input type="password" id="password" name="password" class="form-control" />
                          </div>
                        </div>

      
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="submit" class="btn btn-primary btn-lg">Login</button>
                        </div>
      
                      </form>
      
                      <h6 class="text-center mt-1" style="color: var(--light-black);">Dont have an account <a href="{% url 'userauth:signup' %}" style="color:black ;"><u>Sign Up</u></a> now!</h6>

                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
      
                      <img src="https://images.pexels.com/photos/40568/medical-appointment-doctor-healthcare-40568.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                        class="img-fluid" alt="Sample image">
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>




      <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Signup</title>
</head>
<body>
    

    <section class="vh-100 bg-image"
    style="background-image: url('https://wallpaperaccess.com/full/958470.jpg');">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
      
                      <form class="mx-1 mx-md-4" method="post">
                        {% csrf_token %}
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="nUsername">User Name</label>
                            <input type="text" name="nUsername" id="nUsername" class="form-control" />
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="nEmail">Your Email</label>
                            <input type="email" name="nEmail" id="nEmail" class="form-control" />
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="nPassword1">Password</label>
                            <input type="password" name="nPassword1" id="nPassword1" class="form-control" />
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="nPassword2">Repeat your password</label>
                            <input type="password" name="nPassword2" id="nPassword2" class="form-control" />
                          </div>
                        </div>
      
      
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="submit" class="btn btn-primary btn-lg">Register</button>
                        </div>
      
                      </form>
      
                      <h6 class="text-center mt-1" style="color: var(--light-black);">Already have an account? <a href="{% url 'userauth:login' %}" style="color:black ;"><u>Login</u></a> now!</h6>


                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2" style="padding-left: 150px;">
      
                      <img src="https://media.istockphoto.com/id/1220315936/vector/doctor-and-patient.jpg?s=612x612&w=0&k=20&c=4fD69h3lCgc3n0-0qhCeDbsH5Dhl8AQ_am9bYmdw1Bs="
                        class="img-fluid" alt="Sample image">
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>




      <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

templates/staffPanel.html
<title>Staff Panel</title>
{% load static %}




{% if user.is_authenticated %}

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <h1 class="text-center mt-5 mb-5">Staff Panel</h1>
    <input class="form-control form-control-lg fs-3 border border-primary" id="myInput" type="text" placeholder="Search Appointment">
    <br>
    
    <div class="table-responsive">
      <table class="table table-bordered table-striped table-hover mx-auto">
          <thead>
            <tr>
              <th class="text-center" scope="col">Time</th>
              <th class="text-center" scope="col">First Name</th>
              <th class="text-center" scope="col">Last Name</th>
              <th class="text-center" scope="col">Service</th>
              <th class="text-center" scope="col">Date</th>
            </tr>
          </thead>
          <tbody id="myTable">
              {% for item in items %}
            <tr>
              <td class="text-center">{{item.day}}</td>
              <td class="text-center">{{item.service}}</td>
              <td class="text-center">{{item.time}}</td>
            </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>

</div>

{% else %}

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5">
  <h1 class="p-2  me-3">First Sign in!</h1>
  <a href="{% url 'userauth:login' %}" class="btn btn-primary text-white">Sign in</a>
</div>

{% endif %}

<!--Staff Panel Search-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
</script>

{% endblock %}

templates/userPanel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UserPanel</title>
</head>
<body background="{%static 'img/1211.jpg' %}" style="background-size: cover; background-color: rgba(117, 63, 8, 0.5); background-blend-mode: multiply;">

    {% if user.is_authenticated %}
<h1 class=" ms-5 mt-5 " style="font-size: 3.5rem;"><center><u>User Panel</u></center></h1>

<center>
<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 " style="padding-top: 10px;">
    <h2 class="" style="font-size: 2rem;">User Info:</h2>
    <ul class="list-group fs-4 mt-3">
            <li class="list-group mt-2">Username: {{ user.username }}</li>
    </ul>
</div>
</center>

<!--Appointment Loop-->
<center>
{% if appointments.count > 0 %}
<div class="mt-5 " style="padding-top: 15px;">
    <h1 class=" ms-5">Appointments:</h1>
    <div class="shadow p-4 mb-3 bg-body bg-body rounded text-black  m-5">
        {% for appointment in appointments %}
        <div class="list-group fs-4 border p-3 mb-3">
            <p class="list-group mt-2">Day: {{ appointment.day }}</p>
            <p class="list-group mt-2">Time: {{ appointment.time }}</p>
            <p class="list-group mt-2">Service: {{ appointment.service }}</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
</center>

{% else %}

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5">
    <h1 class="p-2  ms-3">First Sign in!</h1>
    <a href="{% url 'login' %}" class="btn btn-primary text-white">Sign in</a>
</div>

{% endif %}
    
</body>
</html>